# Classifiers

In [12]:
%%latex
Define H for a tridimensional space given two trajectories x and y in J temporary points.
$$
member(T_{c},T_{0}) = 1 - \frac{1}{|J|} \cdot min(\frac{|T_{c} - T_{0}|}{\sigma_{0}},0)
$$

<IPython.core.display.Latex object>

In [40]:
from sklearn.metrics.pairwise import euclidean_distances
import numpy as np
from scipy.spatial import distance

In [41]:
distance.euclidean([1,2,2],[3,2,1])

2.2360679774997898

In [22]:
_x = np.array([[1,1],[1,1],[-1,-1],[1,1],[1,1],[-1,-1]])
test_data = []

for i in range(0,3):
    
    test_data.append(np.random.random((len(_x),2)) * 2 - 1)
    
test_data = np.array(test_data)

In [24]:
test_data.mean(axis=0)

array([[ 0.45173611, -0.25257566],
       [ 0.11680142, -0.42235576],
       [ 0.10642228,  0.41481876],
       [-0.08311998, -0.54734952],
       [-0.03740297,  0.17773099],
       [ 0.25159152, -0.0275533 ]])

In [27]:
for i in range(len(test_data)):
    print(test_data[i])

[[ 0.86418777  0.50144658]
 [ 0.68054859 -0.24998229]
 [ 0.11298603  0.86449592]
 [-0.86813666 -0.66782287]
 [-0.6463117   0.56121652]
 [ 0.10360538  0.35077476]]
[[-0.50252068 -0.7847433 ]
 [ 0.0803107  -0.06340696]
 [ 0.96185706 -0.01336043]
 [ 0.33656893 -0.53380602]
 [ 0.49320943  0.8752443 ]
 [ 0.6997608  -0.48873646]]
[[ 0.99354123 -0.47443026]
 [-0.41045504 -0.95367803]
 [-0.75557624  0.3933208 ]
 [ 0.28220778 -0.44041967]
 [ 0.04089337 -0.90326786]
 [-0.04859162  0.05530179]]


In [30]:
avg = test_data.mean(axis=0)

In [37]:
np.transpose(test_data,[1,0,2])[0]

(3, 2)

In [52]:
def compute_membership_scores(trajectory, bicluster, mean_trajectory):
    
    def compute_deviation(column, mean_coord):
        
        distances = np.array([distance.euclidean(row, mean_coord) for row in column])
        
        return np.std(distances)
        
        
    scores = list()
    j=0
    biclusterT = np.transpose(bicluster,[1,0,2])
    
    for column in biclusterT:
        
        deviation = compute_deviation(column, mean_trajectory[j])
        norm = np.linalg.norm(trajectory[j] - mean_trajectory[j])
        score = min(deviation/norm, 1)
        scores.append(score)
        j += 1
        
    return np.array(scores)

In [53]:
def member(tc, bicluster):
    
    _tc = tc
    _bicluster = bicluster
    mean_trajectory = bicluster.mean(axis=0)
    scores = compute_membership_scores(_tc, bicluster, mean_trajectory)
    total_membership_score = 1.0 - ((1 / len(tc)) *sum(scores))
    
    return total_membership_score

In [54]:
member(_x,test_data)

0.8885733295886411