# Tridimensional Coherence

In [1]:
%%latex
Define H for a tridimensional space given two trajectories x and y in J temporary points.
$$
H_{+}(x,y,J) = 1 - \frac{1}{|J|} \cdot \sum \limits_{j \in J }|((x_{j},\bar{x}) - (y_{j},\bar{y})|
$$

<IPython.core.display.Latex object>

In [2]:
%%latex
Define H for a new term 'z' in X
$$
H_{1}(I,J,X,z) =H_{0}(I,J,X) \cdot \frac{(I-1)}{(I+1)} + \frac{|2|}{(I)(I+1)} \cdot \sum_{x \epsilon X} {h(x,z,J)}
$$

<IPython.core.display.Latex object>

In [3]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import math

from mpl_toolkits.mplot3d import Axes3D

In [4]:
_x = np.array([[0.0,0.0],[0.25,0.25],[0.5,0.5],[0.25,0.25],[0.0,0.0],[-0.25,-0.25]])
_y = np.array([[0.0,0.0],[-0.25,-0.25],[-0.5,-0.5],[0.25,0.25],[0.0,0.0],[0.0,0.25]])
len(_x)

6

In [5]:
np.mean(_x,axis=0)

array([ 0.125,  0.125])

In [6]:
np.mean(_y, axis=0)

array([-0.08333333, -0.04166667])

In [7]:
math.hypot(_x[0][0]-np.mean(_x,axis=0)[0],_x[0][1]-np.mean(_x,axis=0)[1])

0.1767766952966369

In [8]:
math.hypot(_y[0][0]-np.mean(_y,axis=0)[0],_y[0][1]-np.mean(_y,axis=0)[1])

0.09316949906249122

def three_dimensional_correlation(x, y):
    
    _x = x
    _y = y
    mean_point_x = np.mean(_x, axis=0)
    mean_point_y = np.mean(_y, axis=0)
    _J = len(_x)
    
    acc = 0
    
    for j in range(0,_J):
        
        x_axis_diff = _x[j][0] - mean_point_x[0]
        y_axis_diff = _x[j][1] - mean_point_x[1]
        
        x_distance = math.hypot(x_axis_diff, y_axis_diff)
        
        x_axis_diff = _y[j][0] - mean_point_y[0]
        y_axis_diff = _y[j][1] - mean_point_y[1]
        
        y_distance = math.hypot(x_axis_diff, y_axis_diff)
        
        diff_term = (x_distance - y_distance) / 2.0
        
        diff_term = diff_term ** 2.0
        
        acc += diff_term
        
    return (1-acc/abs(_J))

In [10]:
three_dimensional_correlation(_x, _y)

0.9936508313301623

In [11]:
_x_test = np.array([[1,1],[1,1],[-1,-1],[1,1],[1,1],[-1,-1]])
_y_test = np.array([[-1,-1],[-1,-1],[1,1],[-1,-1],[-1,-1],[1,1]])

In [12]:
three_dimensional_correlation(_x_test, _y)

0.7392698824122184

def three_dimensional_pair_coherence(X):
    
    _I = len(X)
    HP = 0
    
    for i in range(0, len(X)):
    
        for j in range(i+1, len(X)):
            
            if i == j:
                
                break
                
            x = X[i]
            y = X[j]
            correlation = three_dimensional_correlation(x,y)
            HP += correlation
            
    HP *= math.fabs(2.0)/(math.fabs(_I)*(math.fabs(_I)-1.0)) if _I > 1 else 0
    
    return HP

## Data generation

In [14]:
test_vectors = np.array([_x]*1)

In [15]:
type(test_vectors)

numpy.ndarray

In [16]:
np.random.random((len(_x),2)) * 2 - 1

array([[ 0.51718754, -0.39015333],
       [-0.56616161,  0.50001387],
       [-0.39639107, -0.23434533],
       [ 0.32241726,  0.94748774],
       [-0.22004499,  0.32998441],
       [ 0.03879684,  0.09037203]])

In [17]:
test_data = []

for i in range(0,100):
    
    test_data.append(np.random.random((len(_x),2)) * 2 - 1)    

In [18]:
len(np.array(test_data))

100

In [19]:
final_test = np.concatenate([np.array(test_data),test_vectors])

In [20]:
len(test_data)

100

In [21]:
len(final_test)

101

In [22]:
print(three_dimensional_pair_coherence(test_data))

0.9552473811835247


In [23]:
print(three_dimensional_pair_coherence(final_test))

0.9548032511558131


In [24]:
final_test.shape

(101, 6, 2)

In [269]:
def three_dimensional_msr(X):
    
    _I = X.shape[0]
    _J = X.shape[1]
    _XiJ = np.mean(X, axis=1)
    _XIj = np.mean(X, axis=0)
    # _XIJ = np.mean(X)
    _XIJ = np.mean(_XiJ, axis = 0)
    acc = 0
    
    for i in range(_I):
        
        tmp = 0
        
        for j in range(_J):
            
            tmp =  (X[i,j] - _XiJ[i] - _XIj[j] + _XIJ)
            tmp = (tmp[0]**2 + tmp[1]**2)
            acc += tmp

    acc = 1-(acc/(_I*_J*2*np.sqrt(2)))
    return acc

In [270]:
final_test[0,0]

array([ 0.23326865,  0.32952037])

In [273]:
_x_test = np.array([[1,1],[-1,1]])
_y_test = np.array([[1,1],[-1,1]])

test = list()
test.append(_x_test)
test.append(_y_test)
np.array(test)

three_dimensional_msr(np.array(test))

1.0

In [274]:
len(_x_test)

2

In [268]:
np.array([1,1]) - 1

array([0, 0])

In [275]:
def three_dimensional_coherence(r1, r2):
    
    aux_list = list()
    aux_list.append(r1)
    aux_list.append(r2)
    
    return three_dimensional_msr(np.array(aux_list))

In [276]:
three_dimensional_correlation(_x_test,_y_test)

1.0