# Tridimensional Coherence

In [110]:
%%latex
Define H for a tridimensional space given two trajectories x and y in J temporary points.
$$
H_{+}(x,y,J) = 1 - \frac{1}{|J|} \cdot \sum \limits_{i \in J } (\frac {(d(x_{j},\bar{x}) - d(y_{j},\bar{y}))}{2})^2
$$

<IPython.core.display.Latex object>

In [3]:
%%latex
Define H for a new term 'z' in X
$$
H_{1}(I,J,X,z) =H_{0}(I,J,X) \cdot \frac{(I-1)}{(I+1)} + \frac{|2|}{(I)(I+1)} \cdot \sum_{x \epsilon X} {h(x,z,J)}
$$

<IPython.core.display.Latex object>

In [101]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import math

from mpl_toolkits.mplot3d import Axes3D

In [108]:
_x = np.array([[0.0,0.0],[0.25,0.25],[0.5,0.5],[0.25,0.25],[0.0,0.0],[-0.25,-0.25]])
_y = np.array([[0.0,0.0],[-0.25,-0.25],[-0.5,-0.5],[0.25,0.25],[0.0,0.0],[0.0,0.25]])
len(_x)

6

In [103]:
np.mean(_x,axis=0)

array([ 0.125,  0.125])

In [104]:
np.mean(_y, axis=0)

array([-0.08333333, -0.04166667])

In [106]:
math.hypot(_x[0][0]-np.mean(_x,axis=0)[0],_x[0][1]-np.mean(_x,axis=0)[1])

0.1767766952966369

In [107]:
math.hypot(_y[0][0]-np.mean(_y,axis=0)[0],_y[0][1]-np.mean(_y,axis=0)[1])

0.09316949906249122

In [127]:
def three_dimensional_correlation(x, y):
    
    _x = x
    _y = y
    mean_point_x = np.mean(_x, axis=0)
    mean_point_y = np.mean(_y, axis=0)
    _J = len(_x)
    
    acc = 0
    
    for j in range(0,_J):
        
        x_axis_diff = _x[j][0] - mean_point_x[0]
        y_axis_diff = _x[j][1] - mean_point_x[1]
        
        x_distance = math.hypot(x_axis_diff, y_axis_diff)
        
        x_axis_diff = _y[j][0] - mean_point_y[0]
        y_axis_diff = _y[j][1] - mean_point_y[1]
        
        y_distance = math.hypot(x_axis_diff, y_axis_diff)
        
        diff_term = (x_distance - y_distance) / 2.0
        
        diff_term = diff_term ** 2.0
        
        acc += diff_term
        
    return (1-acc/abs(_J))

In [128]:
three_dimensional_correlation(_x, _y)

0.9936508313301623

In [129]:
_x_test = np.array([[1,1],[1,1],[-1,-1],[1,1],[1,1],[-1,-1]])
_y_test = np.array([[-1,-1],[-1,-1],[1,1],[-1,-1],[-1,-1],[1,1]])

In [130]:
three_dimensional_correlation(_x_test, _y)

0.7392698824122184

In [176]:
def three_dimensional_pair_coherence(X):
    
    _I = len(X)
    HP = 0
    
    for i in range(0, len(X)):
    
        for j in range(i+1, len(X)):
            
            if i == j:
                
                break
                
            x = X[i]
            y = X[j]
            correlation = three_dimensional_correlation(x,y)
            HP += correlation
            
    HP *= math.fabs(2.0)/(math.fabs(_I)*(math.fabs(_I)-1.0)) if _I > 1 else 0
    
    return HP

## Data generation

In [189]:
test_vectors = np.array([_x]*150)

In [190]:
type(test_vectors)

numpy.ndarray

In [191]:
np.random.random((len(_x),2)) * 2 - 1

array([[ 0.1118072 ,  0.53618213],
       [ 0.26716921,  0.17542077],
       [-0.59214939, -0.62336867],
       [ 0.75355371,  0.96258808],
       [-0.80246502,  0.3085691 ],
       [-0.92651494, -0.02001667]])

In [192]:
test_data = []

for i in range(0,100):
    
    test_data.append(np.random.random((len(_x),2)) * 2 - 1)    

In [193]:
len(np.array(test_data))

100

In [194]:
final_test = np.concatenate([np.array(test_data),test_vectors])

In [195]:
len(test_data)

100

In [196]:
len(final_test)

250

In [197]:
print(three_dimensional_pair_coherence(test_data))

0.9584999051262449


In [184]:
print(three_dimensional_pair_coherence(final_test))

0.9638017427284089
