# Tridimensional Coherence

In [8]:
%%latex
Define H for a tridimensional space given two trajectories x and y in J temporary points.
$$
H_{+}(x,y,J) = 1 - \frac{1}{|J|} \cdot \sum \limits_{j \in J }|((x_{j},\bar{x}) - (y_{j},\bar{y})|
$$

<IPython.core.display.Latex object>

In [3]:
%%latex
Define H for a new term 'z' in X
$$
H_{1}(I,J,X,z) =H_{0}(I,J,X) \cdot \frac{(I-1)}{(I+1)} + \frac{|2|}{(I)(I+1)} \cdot \sum_{x \epsilon X} {h(x,z,J)}
$$

<IPython.core.display.Latex object>

In [9]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import math

from mpl_toolkits.mplot3d import Axes3D

In [10]:
_x = np.array([[0.0,0.0],[0.25,0.25],[0.5,0.5],[0.25,0.25],[0.0,0.0],[-0.25,-0.25]])
_y = np.array([[0.0,0.0],[-0.25,-0.25],[-0.5,-0.5],[0.25,0.25],[0.0,0.0],[0.0,0.25]])
len(_x)

6

In [11]:
np.mean(_x,axis=0)

array([ 0.125,  0.125])

In [12]:
np.mean(_y, axis=0)

array([-0.08333333, -0.04166667])

In [13]:
math.hypot(_x[0][0]-np.mean(_x,axis=0)[0],_x[0][1]-np.mean(_x,axis=0)[1])

0.1767766952966369

In [14]:
math.hypot(_y[0][0]-np.mean(_y,axis=0)[0],_y[0][1]-np.mean(_y,axis=0)[1])

0.09316949906249122

In [15]:
def three_dimensional_correlation(x, y):
    
    _x = x
    _y = y
    mean_point_x = np.mean(_x, axis=0)
    mean_point_y = np.mean(_y, axis=0)
    _J = len(_x)
    
    acc = 0
    
    for j in range(0,_J):
        
        x_axis_diff = _x[j][0] - mean_point_x[0]
        y_axis_diff = _x[j][1] - mean_point_x[1]
        
        x_distance = math.hypot(x_axis_diff, y_axis_diff)
        
        x_axis_diff = _y[j][0] - mean_point_y[0]
        y_axis_diff = _y[j][1] - mean_point_y[1]
        
        y_distance = math.hypot(x_axis_diff, y_axis_diff)
        
        diff_term = (x_distance - y_distance) / 2.0
        
        diff_term = diff_term ** 2.0
        
        acc += diff_term
        
    return (1-acc/abs(_J))

In [16]:
three_dimensional_correlation(_x, _y)

0.9936508313301623

In [17]:
_x_test = np.array([[1,1],[1,1],[-1,-1],[1,1],[1,1],[-1,-1]])
_y_test = np.array([[-1,-1],[-1,-1],[1,1],[-1,-1],[-1,-1],[1,1]])

In [18]:
three_dimensional_correlation(_x_test, _y)

0.7392698824122184

In [19]:
def three_dimensional_pair_coherence(X):
    
    _I = len(X)
    HP = 0
    
    for i in range(0, len(X)):
    
        for j in range(i+1, len(X)):
            
            if i == j:
                
                break
                
            x = X[i]
            y = X[j]
            correlation = three_dimensional_correlation(x,y)
            HP += correlation
            
    HP *= math.fabs(2.0)/(math.fabs(_I)*(math.fabs(_I)-1.0)) if _I > 1 else 0
    
    return HP

## Data generation

In [75]:
test_vectors = np.array([_x]*1)

In [76]:
type(test_vectors)

numpy.ndarray

In [77]:
np.random.random((len(_x),2)) * 2 - 1

array([[-0.78735359, -0.50542931],
       [-0.51444957, -0.69731373],
       [ 0.19398257,  0.11237966],
       [-0.42936901,  0.55430711],
       [-0.57632876, -0.90617352],
       [ 0.74663779, -0.52163979]])

In [78]:
test_data = []

for i in range(0,100):
    
    test_data.append(np.random.random((len(_x),2)) * 2 - 1)    

In [79]:
len(np.array(test_data))

100

In [80]:
final_test = np.concatenate([np.array(test_data),test_vectors])

In [81]:
len(test_data)

100

In [82]:
len(final_test)

101

In [83]:
print(three_dimensional_pair_coherence(test_data))

0.9560632337467876


In [84]:
print(three_dimensional_pair_coherence(final_test))

0.9556599059101568


In [85]:
final_test.shape

(101, 6, 2)

In [112]:
def three_dimensional_msr(X):
    
    _I = X.shape[0]
    _J = X.shape[1]
    _XiJ = np.mean(X, axis=1)
    _XIj = np.mean(X, axis=0)
    _XIJ = np.mean(X)
    
    acc = 0
    
    for i in range(_I):
        
        tmp = 0
        
        for j in range(_J):
            
            tmp =  (X[i,j] - _XiJ[i] - _XIj[j] + _XIJ)
            print(tmp)
            tmp = (tmp[0]**2 + tmp[1]**2)**1/2
            acc += tmp
    acc = 1-(acc/(_I*_J))
        
    return acc

In [113]:
final_test[0,0]

array([-0.42842774, -0.62106482])

In [114]:
three_dimensional_msr(final_test)

(6, 2)
(101, 2)
-0.00259371979145
[-0.61856453 -0.31072207]
[-0.38730821 -0.46901441]
[ 0.16773021 -0.3819408 ]
[ 0.28097571  0.77352659]
[-0.09619901 -0.31838346]
[ 0.60838339  0.7515166 ]
[-0.8712179  -0.17359465]
[ 0.47063737 -0.57981378]
[ 0.10900271 -0.16962379]
[ 0.63962491  0.81638219]
[-0.1872933   0.09631433]
[-0.20573625  0.05531815]
[ 0.01119859  0.45210337]
[-0.2548367   0.14639694]
[ 0.5717703  -0.86791458]
[ 0.64313961 -0.10583955]
[-0.00189604 -0.06697297]
[-1.01435821  0.48720924]
[ 0.95861994  0.4314778 ]
[-0.40727923  0.25136043]
[-0.13509268 -0.73309902]
[-0.71599932 -0.03937728]
[ 0.84273569  0.11413951]
[-0.58796686  0.02048102]
[-0.85471045 -0.15725278]
[ 0.82688748  0.926763  ]
[ 0.54549593 -0.4836791 ]
[ 0.18908435  0.28366267]
[-0.02194978 -0.12726455]
[-0.72978998 -0.39724678]
[-0.2877122  -0.00931501]
[ 0.82458746  0.22641779]
[ 0.6549762   0.42262486]
[-0.27297607 -0.71218029]
[-0.32780956  0.48559088]
[-0.63604829 -0.36815578]
[-0.80508329 -0.39304832]
[ 0.

[ 0.09482494 -0.38568309]
[-0.71919864  1.0611578 ]
[ 0.97328476  0.34091896]
[-0.16340951 -0.67340243]
[-0.50964277 -0.11147038]
[ 0.55551348  0.41812613]
[-0.53651142  0.89494558]
[-0.36421699 -0.82413541]
[-0.53649597 -0.64093234]
[-0.54549322  0.34123047]
[-0.17862266 -0.21408998]
[ 0.40996859  0.18264016]
[ 0.90297631  0.13370098]
[-0.09731551  0.24243317]
[ 0.32126266  0.19828256]
[ 0.01983522 -0.45455378]
[-0.02169397 -0.36798656]
[-0.94373015  0.17290962]
[-0.06160955  0.35876724]
[ 0.64095333  0.13756338]
[-0.2717818   0.23054222]
[-0.73896809  0.15891201]
[-0.98527772 -1.2230075 ]
[ 0.54914003  0.47615999]
[ 0.68775115  0.25938036]
[ 0.71415398  0.14299538]
[ 0.77327873  0.83806004]
[-0.59456961  0.85627703]
[ 0.06243862 -0.51683121]
[-0.29898893 -0.8493042 ]
[ 0.1455946  -0.70161038]
[-0.13273588  0.41839116]
[ 0.69660466 -0.04586005]
[ 0.49692329  0.82343598]
[ 0.61384118 -0.24937874]
[-0.20384819 -0.77035874]
[-0.54012231 -0.55967451]
[-1.1083811   0.84681851]
[-0.19737568

0.73617126139837064